Correct full and right footpad switch state
Relys/vesc_pkg pull request #1
Opened 2024-11-23 04:00 UTC by Defying

2024-11-23 08:09 UTC, contactsimonwilson requested changes

2024-11-23 08:09 UTC, contactsimonwilson commented on float_accessories/lib/can.lisp
> +                                (def footpad-adc1-t (/ (bufget-u8 data 11) 50))
These need to be made floats before the conversion
```suggestion
                                (def footpad-adc1-t (/ (to-float (bufget-u8 data 11)) 50))
```

2024-11-25 02:18 UTC, Relys commented
Had been fixed internally. Just pushed large commit.

2024-11-25 02:26 UTC, contactsimonwilson commented
@Relys isn't the fix for the ADC voltages still missing from the latest commit?

2024-12-03 06:30 UTC, Relys commented
Implemented

2024-12-03 06:30 UTC, closed without merging